import = [
    "~/.config/alacritty/themes/catppuccin-frappe.toml"
]

[font]
size=12.0

[font.normal]
family = "JetBrainsMonoNL Nerd Font"
style = "Regular"

[font.bold]
family = "JetBrainsMonoNL Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMonoNL Nerd Font"
style = "Italic"

[font.bold_italic]
family = "JetBrainsMonoNL Nerd Font"
style = "Italic"

